name: kakaaga
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.3
  flutter_typeahead: ^3.1.1 # see if you use it anywhere
  flutter_card_swipper: ^0.4.0
  intl: ^0.17.0
  font_awesome_flutter: ^9.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  cloud_firestore: ^1.0.4
  firebase_storage: ^8.0.3
  firebase_auth: ^1.0.3
  flutter_spinkit: ^5.0.0
  email_validator: ^2.0.1
  shared_preferences: ^2.0.5 # I'M UNABLE TO MAKE THIS WORK
  provider: ^5.0.0
  file_picker: ^3.0.1
  flutter_slidable: ^0.6.0
  loading_overlay: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # TODO: delete assets once finished using them
  assets:
   - assets/

